#!/bin/bash

# Read JSON and extract values
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1 / 10}')
height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1 / 10}')

# Output formatted string
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
